theme: jekyll-theme-cayman
defaults: # defaults that fit the criteria - ref: https://jekyllrb.com/docs/configuration/front-matter-defaults/
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      email: "nextcalc.feedback@gmail@@@com"